- name: Deploy to EC2
  hosts: localhost
  connection: local

  tasks: 
    - name: Launch EC2 Instance
      ec2_instance: 
        instance_type: t2.micro
        image_id: ami-04e5276ebb8451442
        region: us-east-1
        key_name: test
        vpc_subnet_id: subnet-0ef7703ceb256fd98
        count: 1
        network:
          assign_public_ip: yes
        wait: yes
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        security_token: "{{ session_token }}"